#!/usr/bin/env bash
printf "Bootstrapping ..."
$CC --std=c++20 -Wno-braced-scalar-init -DNOW_BOOTSTRAP main.cpp -o app.exe
if [ $? -ne 0 ]; then
    echo "ERR: Unable to compile bootstrap!"
    exit 1
fi
./app.exe build
printf "\rBootstrapping is done. Run ./app.exe to start.\n"
