#!/usr/bin/env bash
printf "Bootstrapping ..."
$CC -O0 -g --std=c++20 -Wno-braced-scalar-init now.cpp -o now
if [ $? -ne 0 ]; then
    echo "ERR: Unable to compile bootstrap!"
else
    printf "\rBootstrapping is done. Run ./now to start.\n"
fi